### ISSUE TITLE
Name this thing

### ISSUE THREAD

**Issue by craigcook** [mozilla/web-design-system#6]
Naming things is hard.

I've been kind of avoiding it, hoping the perfect name would come along and suggest itself organically. But in so avoiding the naming I have somehow also prevented a name from suggesting itself. By deliberately not naming it I've come up totally blank when trying to think of a good name. We just keep talking about "the system" and that's just not going to work long term. 

We're now at the point that we need to be able to refer to things more specifically. E.g. this system currently contains a modified copy of the Pebbles framework taken from Bedrock, but this copy of Pebbles is already very different from the original. It can no longer accurately be called Pebbles, it needs something to make it distinct and separate. If only because we have to name the folder. We can't really start integrating system styles into Bedrock because there would be collisions with pre-existing Pebbles.

So let's start to put real thought into choosing a name for the system, its accompanying CSS framework, and even the system tool itself now that it's deviated significantly from Drizzle.

A few suggested names already are "Protocol" (which was the code name for the design concept that became the new Mozilla logo) and "Spark" (which I think came from something Chris Beard said in the plenary at the Austin all-hands in 2017). 

I would love to make it some semi-obscure pop-culture reference if possible but that needn't be a requirement, just a strong desire for some extra awesomeness and whimsy.

**Comment by craigcook** [comment]
Looks like there's a design system called Spark being developed by Quicken Loans https://sparkdesignsystem.com/ so that probably crosses that name off the list. Incidentally they're also using a customized Drizzle with some neat additions I might have to steal.

**Comment by craigcook** [comment]
Suggestion: **Spinner**

As in "web spinner" which is also a roundabout Spider-Man reference, as well as a Blade Runner reference (the flying police cars are called Spinners). There's even a logo.

![image](https://user-images.githubusercontent.com/205591/37165603-ea137d6c-22b1-11e8-8a81-cdaca3c73564.png)

**Comment by stephaniehobson** [comment]
I like Protocol. 🚢

**Comment by dzingeek** [comment]
let's use this doc so we don't have to scroll forever in github. please add to the list, silly and odd is fine it might spark an idea or start a convo.

https://docs.google.com/document/d/1YYhspjC_6NGvPbq6pwZyV9wX-tp-WK-eMDwsDuWjA_Y/edit?usp=sharing

**Comment by alexgibson** [comment]
I really hope this doesn't need it's own google doc 😉 +1 for Protocol here!

**Comment by craigcook** [comment]
I didn't want to start voting yet, I wanted to get a list of candidates...

**Comment by alexgibson** [comment]
I know naming things is both hard and important, but I'd try not to drag this one out too long (just my 2 cents).

**Comment by craigcook** [comment]
Right, I just also didn't want to latch onto the first idea in case something better comes along. Let's keep it open to suggestions for a day or two, but so far Protocol is the early leader.

**Comment by craigcook** [comment]
After all other suggestions failed to gain traction, **Protocol** is the clear favorite.

It was the design code name for [the concept that became the Mozilla logo](https://blog.mozilla.org/opendesign/design-route-d-protocol/). It's a techie/webby term, ties directly to the history of the brand, and as far as I've been able to determine via searching isn't being used as a name for any other framework/design system type thing nor any other Mozilla projects.
